source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Zoetrope_Example', :exclusive => true do
  pod "Zoetrope", :path => "../"
end

target 'Zoetrope_Tests', :exclusive => true do
  pod "Zoetrope", :path => "../"

  
end
